name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Run tests
        run: |
          poetry install
          poetry run pytest --cov=iris_client --cov-report=xml
        env:
          IRIS_BASE_URL: ${{ secrets.IRIS_BASE_URL }}
          IRIS_USERNAME: ${{ secrets.IRIS_USERNAME }}
          IRIS_PASSWORD: ${{ secrets.IRIS_PASSWORD }}
      - uses: codecov/codecov-action@v2
