name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Install package
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=iris_client --cov-report=xml
        env:
          IRIS_BASE_URL: ${{ secrets.IRIS_BASE_URL }}
          IRIS_USERNAME: ${{ secrets.IRIS_USERNAME }}
          IRIS_PASSWORD: ${{ secrets.IRIS_PASSWORD }}
        if: github.actor != 'dependabot[bot]'
      - uses: codecov/codecov-action@v3

  pypi:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-python-action@v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          upload: ${{ startsWith(github.ref, 'refs/tags/v') }}
